-- Tabela para armazenar as informações dos usuários (clientes, vendedores e administradores).
CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL DEFAULT '',
    sobrenome VARCHAR(255) DEFAULT '',
    email VARCHAR(150) NOT NULL UNIQUE,
    senha TEXT,
    tipo_usuario VARCHAR(20) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_tipo_check 
        CHECK (tipo_usuario IN ('CLIENTE','VENDEDOR','ADMIN'))
);

-- Tabela para armazenar as categorias dos produtos.
CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao TEXT
);

-- Tabela para definir os atributos possíveis que os produtos podem ter (ex: cor, peso, tamanho).
CREATE TABLE atributo (
    id_atributo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    unidade VARCHAR(20),
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela para armazenar os dados gerais base dos produtos, vinculados a uma categoria.
CREATE TABLE produto (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    marca VARCHAR(100),
    modelo VARCHAR(150),
    fabricante VARCHAR(255),
    id_categoria BIGINT NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

-- Tabela associativa que relaciona quais atributos são aplicáveis a quais categorias.
CREATE TABLE categoria_atributo (
    id_categoria BIGINT NOT NULL,
    id_atributo BIGINT NOT NULL,
    PRIMARY KEY (id_categoria, id_atributo),
    CONSTRAINT fk_cat_atr_categoria
        FOREIGN KEY (id_categoria) REFERENCES categoria(id) ON DELETE CASCADE,
    CONSTRAINT fk_cat_atr_atributo
        FOREIGN KEY (id_atributo) REFERENCES atributo(id_atributo) ON DELETE CASCADE
);

-- Tabela associativa que armazena os valores específicos dos atributos para cada produto.
CREATE TABLE produto_atributo (
    id_produto BIGINT NOT NULL,
    id_atributo BIGINT NOT NULL,
    valor_string VARCHAR(255),
    valor_number NUMERIC(10,2),
    valor_boolean BOOLEAN,
    PRIMARY KEY (id_produto, id_atributo),
    CONSTRAINT fk_prod_atr_produto
        FOREIGN KEY (id_produto) REFERENCES produto(id_produto) ON DELETE CASCADE,
    CONSTRAINT fk_prod_atr_atributo
        FOREIGN KEY (id_atributo) REFERENCES atributo(id_atributo) ON DELETE CASCADE
);

-- Tabela para armazenar os anúncios dos produtos criados pelos vendedores, incluindo preço e estoque.
CREATE TABLE anuncio (
    id_anuncio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vendedor BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL,
    estoque INTEGER DEFAULT 0,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anuncio_produto
        FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
    CONSTRAINT fk_anuncio_vendedor
        FOREIGN KEY (id_vendedor) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- Tabela para armazenar as URLs e metadados das imagens associadas aos produtos e anúncios.
CREATE TABLE produto_imagem (
    id_imagem BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto BIGINT NOT NULL,
    id_anuncio BIGINT,
    url TEXT NOT NULL,
    nome_arquivo VARCHAR(255),
    ordem INTEGER DEFAULT 0,
    principal BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_imagem_produto
        FOREIGN KEY (id_produto) REFERENCES produto(id_produto) ON DELETE CASCADE,
    CONSTRAINT fk_imagem_anuncio
        FOREIGN KEY (id_anuncio) REFERENCES anuncio(id_anuncio)
);

-- Tabela para registrar os pedidos feitos pelos clientes, guardando um 'snapshot' do endereço de entrega.
CREATE TABLE pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    logradouro_snap VARCHAR(255) NOT NULL,
    numero_snap VARCHAR(10) NOT NULL,
    cidade_snap VARCHAR(100) NOT NULL,
    estado_snap VARCHAR(100) NOT NULL,
    cep_snap VARCHAR(9) NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (id_cliente) REFERENCES usuarios(id_usuario)
);

-- Tabela para armazenar os itens individuais de cada pedido, relacionando-os aos anúncios comprados.
CREATE TABLE pedido_item (
    id_pedido_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_anuncio BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco NUMERIC(10,2) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_item_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_item_anuncio
        FOREIGN KEY (id_anuncio) REFERENCES anuncio(id_anuncio)
);

-- Tabela para armazenar os endereços cadastrados pelos usuários.
CREATE TABLE usuario_endereco (
    id_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado CHAR(2) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_endereco_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);